# Generated by Django 4.1.3 on 2022-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('minutes', models.IntegerField(verbose_name='minutes')),
                ('contributor_id', models.IntegerField(verbose_name='contributor_id')),
                ('submitted', models.DateField(max_length=35, verbose_name='submitted')),
                ('tags', models.CharField(max_length=1024, verbose_name='tags')),
                ('nutrition', models.CharField(max_length=255, verbose_name='nutrition')),
                ('n_steps', models.IntegerField(verbose_name='n_steps')),
                ('steps', models.CharField(max_length=1024, verbose_name='steps')),
                ('description', models.CharField(max_length=1024, verbose_name='description')),
                ('ingredients', models.CharField(max_length=1024, verbose_name='ingredients')),
                ('n_ingredients', models.IntegerField(verbose_name='n_ingredients')),
                ('recipe_id', models.IntegerField(verbose_name='recipe_id')),
                ('average_rating', models.FloatField(max_length=35, verbose_name='average_rating')),
                ('votes', models.IntegerField(verbose_name='votes')),
                ('like', models.IntegerField(verbose_name='like')),
            ],
        ),
    ]
